bases:
- ../driver
- rbac

resources:
- driverinfo-beta.yaml

# The RBAC files must match the image versions.
images:
- name: quay.io/k8scsi/csi-provisioner
  newTag: v1.6.0
- name: quay.io/k8scsi/csi-node-driver-registrar
  newTag: v1.2.0
