apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: my-csi-app
spec:
  selector:
    matchLabels:
      app: my-csi-app
  replicas: 2
  template:
    metadata:
      labels:
        app: my-csi-app
    spec:
      # The 'pmem-csi-driver-test' container runs apps as user/group 1000/1000.
      # This security context causes permissions of volume mounts
      # to be adapted accordingly, see
      # https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
      securityContext:
        fsGroup: 1000
      # make sure that no two Pods run on same node
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: [ my-csi-app ]
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: my-frontend
        image: intel/pmem-csi-driver-test:canary
        command: [ "/bin/sh" ]
        args: [ "-c", "touch /data/$(POD_NAME); sleep 100000" ]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: "/data"
          name: my-csi-volume
      volumes:
      - name: my-csi-volume
        persistentVolumeClaim:
          claimName: pmem-csi-pvc-cache
