apiVersion: pmem-csi.intel.com/v1alpha1
kind: Deployment
metadata:
  name: pmem-csi.intel.com
spec:
  deviceMode: "lvm"
  nodeSelector:
    # When using Node Feature Discovery (NFD):
    feature.node.kubernetes.io/memory-nv.dax: "true"
    # When using manual node labeling with that label:
    # storage: pmem

