bases:
- ../kubernetes-base-lvm-testing

patches:
- ../patches/driverinfo-storage-capacity-patch.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pmem-csi-intel-com-controller
  path: ../patches/external-provisioner-storage-capacity-patch.yaml
