bases:
- ../driver
- rbac

resources:
- driverinfo-beta.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pmem-csi-controller
  path: ../patches/strict-topology-patch.yaml

# The RBAC files must match the image versions.
images:
- name: quay.io/k8scsi/csi-provisioner
  newTag: v1.2.1
- name: quay.io/k8scsi/csi-node-driver-registrar
  newTag: v1.1.0
