apiVersion: pmem-csi.intel.com/v1alpha1
kind: Deployment
metadata:
  name: example-deployment
spec:
  namespace: default
  image:
    registry: 172.17.0.1:5000
    name: pmem-csi-driver
    tag: canary
  controller:
    resources:
      request:
        cpu: "200m"
        memory: "100Mi"
  node:
    deviceMode: lvm
    resources:
      requests:
        cpu: "200m"
        memory: "100Mi"

