bases:
- ../kubernetes-1.14-direct-testing/

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pmem-csi-controller
  path: ../testing/controller-coverage-patch.yaml

- target:
    group: apps
    version: v1beta2
    kind: DaemonSet
    name: pmem-csi-node
  path: ../testing/node-coverage-patch.yaml

images:
- name: 192.168.8.1:5000/pmem-csi-driver
  newName: 192.168.8.1:5000/pmem-csi-driver-test

