apiVersion: v1
kind: ServiceAccount
metadata:
  name: pmem-csi-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pmem-csi-external-provisioner-cfg
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pmem-csi-external-provisioner-runner
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - get
  - list
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pmem-csi-csi-provisioner-role-cfg
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pmem-csi-external-provisioner-cfg
subjects:
- kind: ServiceAccount
  name: pmem-csi-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pmem-csi-csi-provisioner-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pmem-csi-external-provisioner-runner
subjects:
- kind: ServiceAccount
  name: pmem-csi-controller
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: pmem-csi-controller
spec:
  ports:
  - port: 10000
  selector:
    app: pmem-csi-controller
---
apiVersion: v1
kind: Service
metadata:
  name: pmem-csi-controller-testing
spec:
  ports:
  - port: 10001
  selector:
    app: pmem-csi-controller
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pmem-csi-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pmem-csi-controller
  serviceName: pmem-csi-controller
  template:
    metadata:
      labels:
        app: pmem-csi-controller
    spec:
      containers:
      - args:
        - -v=3
        - -drivername=pmem-csi.intel.com
        - -mode=controller
        - -endpoint=unix:///csi/csi-controller.sock
        - -registryEndpoint=tcp://0.0.0.0:10000
        - -nodeid=$(KUBE_NODE_NAME)
        - -caFile=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - -certFile=/certs/pmem-csi-registry.crt
        - -keyFile=/certs/pmem-csi-registry.key
        - -v=5
        - -testEndpoint
        - -coverprofile=/var/lib/pmem-csi-coverage/pmem-csi-driver-controller-*.out
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: TERMINATION_LOG_PATH
          value: /tmp/termination-log
        image: intel/pmem-csi-driver-test:v0.6.10
        imagePullPolicy: Always
        name: pmem-driver
        securityContext:
          privileged: true
        terminationMessagePath: /tmp/termination-log
        volumeMounts:
        - mountPath: /certs/
          name: registry-cert
        - mountPath: /csi
          name: plugin-socket-dir
        - mountPath: /var/lib/pmem-csi-coverage
          name: coverage-dir
      - args:
        - --timeout=5m
        - --v=3
        - --csi-address=/csi/csi-controller.sock
        - --feature-gates=Topology=true
        - --strict-topology=true
        - -v=5
        image: quay.io/k8scsi/csi-provisioner:v1.2.1
        imagePullPolicy: Always
        name: external-provisioner
        volumeMounts:
        - mountPath: /csi
          name: plugin-socket-dir
      - args:
        - -s
        - tcp-listen:10001,fork,reuseaddr
        - unix-connect:/csi/csi-controller.sock
        image: alpine/socat:1.0.3
        name: socat
        volumeMounts:
        - mountPath: /csi
          name: plugin-socket-dir
      serviceAccount: pmem-csi-controller
      volumes:
      - emptyDir: null
        name: plugin-socket-dir
      - name: registry-cert
        secret:
          items:
          - key: tls.crt
            path: pmem-csi-registry.crt
          - key: tls.key
            path: pmem-csi-registry.key
          secretName: pmem-csi-registry-secrets
      - hostPath:
          path: /var/lib/pmem-csi-coverage
          type: DirectoryOrCreate
        name: coverage-dir
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pmem-csi-node
spec:
  selector:
    matchLabels:
      app: pmem-csi-node
  template:
    metadata:
      labels:
        app: pmem-csi-node
    spec:
      containers:
      - args:
        - -deviceManager=ndctl
        - -v=3
        - -drivername=pmem-csi.intel.com
        - -mode=node
        - -endpoint=$(CSI_ENDPOINT)
        - -nodeid=$(KUBE_NODE_NAME)
        - -controllerEndpoint=tcp://$(KUBE_POD_IP):10001
        - -registryEndpoint=$(PMEM_CSI_CONTROLLER_PORT_10000_TCP)
        - -caFile=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - -certFile=/certs/$(KUBE_NODE_NAME).crt
        - -keyFile=/certs/$(KUBE_NODE_NAME).key
        - -statePath=/var/lib/pmem-csi.intel.com
        - -v=5
        - -testEndpoint
        - -coverprofile=/var/lib/pmem-csi-coverage/pmem-csi-driver-node-*.out
        env:
        - name: CSI_ENDPOINT
          value: unix:///var/lib/pmem-csi.intel.com/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: TERMINATION_LOG_PATH
          value: /tmp/termination-log
        image: intel/pmem-csi-driver-test:v0.6.10
        imagePullPolicy: Always
        name: pmem-driver
        securityContext:
          privileged: true
        terminationMessagePath: /tmp/termination-log
        volumeMounts:
        - mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi
          mountPropagation: Bidirectional
          name: mountpoint-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: pods-dir
        - mountPath: /certs/
          name: registry-cert
        - mountPath: /dev
          name: dev-dir
        - mountPath: /var/lib/pmem-csi.intel.com
          name: pmem-state-dir
        - mountPath: /sys
          name: sys-dir
        - mountPath: /var/lib/pmem-csi-coverage
          name: coverage-dir
      - args:
        - -v=3
        - --kubelet-registration-path=/var/lib/pmem-csi.intel.com/csi.sock
        - --csi-address=/pmem-csi/csi.sock
        - -v=5
        image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
        imagePullPolicy: Always
        name: driver-registrar
        volumeMounts:
        - mountPath: /pmem-csi
          name: pmem-state-dir
        - mountPath: /registration
          name: registration-dir
      hostNetwork: true
      nodeSelector:
        storage: pmem
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: DirectoryOrCreate
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet/plugins/kubernetes.io/csi
          type: DirectoryOrCreate
        name: mountpoint-dir
      - hostPath:
          path: /var/lib/kubelet/pods
          type: DirectoryOrCreate
        name: pods-dir
      - name: registry-cert
        secret:
          secretName: pmem-csi-node-secrets
      - hostPath:
          path: /var/lib/pmem-csi.intel.com
          type: DirectoryOrCreate
        name: pmem-state-dir
      - hostPath:
          path: /dev
          type: DirectoryOrCreate
        name: dev-dir
      - hostPath:
          path: /sys
          type: DirectoryOrCreate
        name: sys-dir
      - hostPath:
          path: /var/lib/pmem-csi-coverage
          type: DirectoryOrCreate
        name: coverage-dir
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pmem-csi-node-testing
spec:
  selector:
    matchLabels:
      app: pmem-csi-node-testing
  template:
    metadata:
      labels:
        app: pmem-csi-node-testing
    spec:
      containers:
      - args:
        - -s
        - tcp-listen:9735,fork,reuseaddr
        - unix-connect:/pmem-csi/csi.sock
        image: alpine/socat:1.0.3
        name: socat
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /pmem-csi
          name: plugin-state-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
        - mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi/pv
          mountPropagation: Bidirectional
          name: staging-dir
      hostNetwork: true
      volumes:
      - hostPath:
          path: /var/lib/pmem-csi.intel.com/
          type: DirectoryOrCreate
        name: plugin-state-dir
      - hostPath:
          path: /var/lib/kubelet/plugins/kubernetes.io/csi/pv
          type: DirectoryOrCreate
        name: staging-dir
      - hostPath:
          path: /var/lib/kubelet/pods
          type: DirectoryOrCreate
        name: mountpoint-dir
---
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: pmem-csi.intel.com
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
