bases:
- ../driver
- rbac

resources:
- driverinfo-storage-capacity.yaml

# The RBAC files must match the image versions.
images:
- name: quay.io/k8scsi/csi-provisioner
  newTag: canary
  newName: localhost:5001/csi-provisioner
- name: quay.io/k8scsi/csi-node-driver-registrar
  newTag: v1.2.0
