# Select LVM mode. The PMEM-CSI driver must be in container #0.
- op: add
  path: /spec/template/spec/containers/0/command/1
  value: "-deviceManager=lvm"

# LVM mode needs init containers.
- op: add
  path: /spec/template/spec/initContainers
  value:
  - name: pmem-ns-init
    image: intel/pmem-csi-driver:canary
    imagePullPolicy: IfNotPresent
    command: ["/usr/local/bin/pmem-ns-init", "-v=3"]
    env:
      - name: TERMINATION_LOG_PATH
        value: /tmp/pmem-ns-init-termination-log
    terminationMessagePath: /tmp/pmem-ns-init-termination-log
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - name: sys-dir
      mountPath: /sys
  - name: pmem-vgm
    image: intel/pmem-csi-driver:canary
    imagePullPolicy: IfNotPresent
    command: ["/usr/local/bin/pmem-vgm", "-v=3"]
    env:
    - name: TERMINATION_LOG_PATH
      value: /tmp/pmem-vgm-termination-log
    terminationMessagePath: /tmp/pmem-vgm-termination-log
    securityContext:
      privileged: true
      runAsUser: 0

# /sys explicit mount added to get around read-only mount
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: sys-dir
    hostPath:
      path: /sys
      type: DirectoryOrCreate
