# Select LVM mode. The PMEM-CSI driver must be in container #0.
- op: add
  path: /spec/template/spec/containers/0/args/0
  value: "-deviceManager=lvm"

# LVM mode needs init containers.
- op: add
  path: /spec/template/spec/initContainers
  value:
  - name: pmem-ns-init
    imagePullPolicy: Always
    image: intel/pmem-csi-driver:v0.6.35
    command: ["/usr/local/bin/pmem-ns-init"]
    args: [ "-v=3" ]
    env:
      - name: TERMINATION_LOG_PATH
        value: /tmp/pmem-ns-init-termination-log
    terminationMessagePath: /tmp/pmem-ns-init-termination-log
    securityContext:
      privileged: true
    volumeMounts:
    - name: sys-dir
      mountPath: /sys
  - name: pmem-vgm
    imagePullPolicy: Always
    image: intel/pmem-csi-driver:v0.6.35
    command: ["/usr/local/bin/pmem-vgm"]
    args: [ "-v=3" ]
    env:
      - name: TERMINATION_LOG_PATH
        value: /tmp/pmem-vgm-termination-log
    terminationMessagePath: /tmp/pmem-vgm-termination-log
    securityContext:
      privileged: true

# /sys explicit mount added to get around read-only mount
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: sys-dir
    hostPath:
      path: /sys
      type: DirectoryOrCreate
